### ISSUE TITLE
pattern make preview-all failures when kustomize: true 

### ISSUE THREAD

**Issue by wadebee** [validatedpatterns/multicloud-gitops#351]
When running ` source pattern.sh make preview-all` I am getting **_Error: Chart.yaml file is missing_** from certain applications.

I expect to see resource yaml output for each application declared in **_values-hub.yaml_**.

This occurs for any applications defined with `kustomize: true `.

Since I was getting a bunch of these errors without insight as to origin I added a debug stmt to common/scripts/preview-all.sh line 13:
        printf "# ------ Switching to app $app in cluster $cluster -------"

Resulting output from preview-all now looks like this.

      # ------ Switching to app compliance-operator in cluster hub -------
      Error: Chart.yaml file is missing

For this specific error my values-hub.yaml looks like this:

```
clusterGroup:
  name: hub
  isHubCluster: true

  subscriptions:
    compliance-operator:
      name: compliance-operator
      namespace: openshift-compliance
      channel: stable

  applications:
    compliance-operator:
      name: compliance-operator
      namespace: openshift-compliance
      project: ekho
      kustomize: true
      path: charts/all/compliance-operator/overlays/default

```

**Comment by mbaldessari** [comment]
Thanks @wadebee . Is https://github.com/validatedpatterns/common/pull/447 sufficient to fix this case? (note that I merged two additional PRs that should improve preview in general https://github.com/validatedpatterns/common/pull/445 and https://github.com/validatedpatterns/common/pull/446)

**Comment by wadebee** [comment]
Thanks @mbaldessari. The three PR's are helpful. 

Could you add below to line 21 in common/scripts/preview-all.sh?

` printf "# Parsing application $app from cluster $cluster\n" `

When preview-all parsing picks up errors within large patterns - it is difficult to identify the problematic declaration. This extra debugging output helps to clarify the context switching going on within the parser.

Below is a problematic section of my preview-all output. I am in the process of troubleshooting these and will get back to you on whether this is a parsing error or (more likely) a problem with my values-hub.yaml.  

This parser is very helpful and already identified a half-dozen problems with my config. It is faster than trying to push the changes through the entire VP GitopS workflow.
```
# Parsing application exho-external-secrets from cluster ngc
Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: null
# Parsing application openshift-compliance from cluster ngc
common/scripts/preview.sh: line 82: kustomize: command not found
# Parsing application openshift-file-integrity from cluster ngc
common/scripts/preview.sh: line 82: kustomize: command not found
# Parsing application openshift-logging from cluster ngc
common/scripts/preview.sh: line 82: kustomize: command not found   
```

**Comment by wadebee** [comment]
There might be a problem with the new parsing? 

The first error from previous message was an obvious typo but the others throwing the line 82 error seem to have valid config (kustomize param). 

Here is a breakout for this app throwing the error:

    openshift-compliance:
      name: openshift-compliance
      namespace: openshift-compliance
      project: ngc
      kustomize: true
      path: charts/all/compliance-operator/overlays/default

**Comment by mbaldessari** [comment]
> Thanks @mbaldessari. The three PR's are helpful.
> 
> Could you add below to line 21 in common/scripts/preview-all.sh?
> 
> `printf "# Parsing application $app from cluster $cluster\n"`

Sure thing I can add that. Should we maybe just error out (i.e. add a set -e to preview.sh) so that errors are caught in a more obvious manner?

> 
> When preview-all parsing picks up errors within large patterns - it is difficult to identify the problematic declaration. This extra debugging output helps to clarify the context switching going on within the parser.
> 
> Below is a problematic section of my preview-all output. I am in the process of troubleshooting these and will get back to you on whether this is a parsing error or (more likely) a problem with my values-hub.yaml.
> 
> This parser is very helpful and already identified a half-dozen problems with my config. It is faster than trying to push the changes through the entire VP GitopS workflow.

That is good to hear. We kind of added it without help text (i.e. it's not shown in make help) to have an idea of what is being rendered, but you're right it can be quite helpful, so it makes sense to fix these issues.

> ```
> # Parsing application exho-external-secrets from cluster foo
> Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: null
> # Parsing application openshift-compliance from cluster foo
> common/scripts/preview.sh: line 82: kustomize: command not found
> # Parsing application openshift-file-integrity from cluster foo
> common/scripts/preview.sh: line 82: kustomize: command not found
> # Parsing application openshift-logging from cluster foo
> common/scripts/preview.sh: line 82: kustomize: command not found   
> ```



> There might be a problem with the new parsing?
> 
> The first error from previous message was an obvious typo but the others throwing the line 82 error seem to have valid config (kustomize param).
> 
> Here is a breakout for this app throwing the error:
> 
> ```
> openshift-compliance:
>   name: openshift-compliance
>   namespace: openshift-compliance
>   project: foo
>   kustomize: true
>   path: charts/all/compliance-operator/overlays/default
> ```

That was a brainfart on my part (I ran it outside the container where I have kustomize installed, the container only has oc, so we should be calling `oc kustomize`), thanks for bringing it up. I have updated https://github.com/validatedpatterns/common/pull/447. Can you let me know if it works for you or if you hit other issues?

**Comment by wadebee** [comment]
This looks much better - all the line: 82 errors have gone away :) 

I like the current preview-all approach where it continues through errors so all files can be parsed. This way - after a single run - I have a complete list of all issues I can address before initiating follow-up runs. 

I still have 3 "non-absolute URL" errors coming from my values files (a hub.yaml and a spoke.yaml). Here are the details of the first error.

```
# Parsing application pgadmin from cluster hub
Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: null
```
I have reviewed the settings and confirmed the path exists and is correct. 

Extract from values-hub.yaml

```
namespaces:
    - ekho-pgadmin:
        operatorGroup: false
        labels:
          foo/owner: "ekho"

applications:
    ekho-pgadmin:
      name: pgadmin
      namespace: ekho-pgadmin
      project: ekho
      kustomize: true
      path: charts/all/pgadmin/overlays/prod
```


Any ideas on what could be causing these errors? I have nearly identical app definitions that parse without issue and the only difference is that they do use operators and have namespace | operatorGroup: true.

**Comment by mbaldessari** [comment]
> This looks much better - all the line: 82 errors have gone away :)

Perfect, thanks. I merged #447 in the meantime

> I like the current preview-all approach where it continues through errors so all files can be parsed. This way - after a single run - I have a complete list of all issues I can address before initiating follow-up runs.

Ack, fair point.

> I still have 3 "non-absolute URL" errors coming from my values files (a hub.yaml and a spoke.yaml). Here are the details of the first error.
> 
> ```
> # Parsing application pgadmin from cluster hub
> Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: null
> ```
> 
> I have reviewed the settings and confirmed the path exists and is correct.
> 
> Extract from values-hub.yaml
> 
> ```
> namespaces:
>     - ekho-pgadmin:
>         operatorGroup: false
>         labels:
>           foo/owner: "ekho"
> 
> applications:
>     ekho-pgadmin:
>       name: pgadmin
>       namespace: ekho-pgadmin
>       project: ekho
>       kustomize: true
>       path: charts/all/pgadmin/overlays/prod
> ```
> 
> Any ideas on what could be causing these errors? I have nearly identical app definitions that parse without issue and the only difference is that they do use operators and have namespace | operatorGroup: true.

I tried to reproduce something here with that namespace definition, but I could not. Does running `oc kustomize charts/all/pgadmin/overlays/prod` give any errors? Any chance you could send me that kustomize bundle so I can try and reproduce it locally?

**Comment by wadebee** [comment]
oc kustomize runs without issue on these errors. 

The pgAdmin example has sensitive output so unable to send that.

But here is the content / detail of the second "non-absolute URL" error with much simpler output.

values-foo.yaml
```
clusterGroup:
  name: foo
  isHubCluster: false

  projects:
    - foo
   
  namespaces:
    - costmanagement-metrics-operator:
        operatorGroup: true
        annotations:
          openshift.io/description: Operator that provides cost management information to cloud.redhat.com
          openshift.io/display-name: Red Hat Cost Management Operator
        targetNamespaces:
          - costmanagement-metrics-operator
  
  subscriptions:
    cost:
      name: costmanagement-metrics-operator
      namespace: costmanagement-metrics-operator
      channel: stable

  applications:
    cost-management-operator:
      name: costmanagement-metrics-operator
      namespace: costmanagement-metrics-operator
      project: foo
      kustomize: true
      path: charts/all/cost-management-operator/overlays/default
```

[cm.zip](https://github.com/validatedpatterns/multicloud-gitops/files/14763564/cm.zip)
