### ISSUE TITLE
Application references to a non-VP GitHub repo within values-xxx.yaml file.

### ISSUE THREAD

**Issue by wadebee** [validatedpatterns/multicloud-gitops#356]
I am trying to get an application entry working in values-hub.yaml that points back to our Enterprise GitHub for its definition.

Here is my values-hub.yaml declaration:

```
clusterGroup:
  applications:
    cost-collector:
      name: cost-collector
      namespace: cost-collector
      project: hub
      kustomize: true
      repoURL: https://github.myenterprise.com/costcollector.git
      path: https://github.myenterprise.com/costcollector/overlays/dev
      targetRevision: main

```
Performing a `. pattern.sh make preview-cost-collector` works without issue and is able to pull all the artifacts from the non-vp repo and runs them successfully through the VP preview pipeline.

However, when I deploy this to the hub cluster via Argo I get the following error:
_Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): https://github.myenterprise.com/costcollector/overlays/dev: app path does not exist_

**Comment by mbaldessari** [comment]
Hi Wade,

I believe the path should be relative to the `repoURL`. So in your case  `path: /overlays/dev` . A quick local test here with kustomize on argo worked okay. Can you try with that?

**Comment by claudiol** [comment]
Hi @wadebee,
  Here's the example we used in our test environment:
  ```
    terminal:
      name: web-terminal
      namespace: cluster-ops
      kustomize: true
      project: cluster-ops
      repoURL: https://github.com/redhat-cop/gitops-catalog
      path: web-terminal/aggregate/overlays/default
      targetRevision: main
 ```
I used one of our redhat-cop gitops-catalog items that deploys the web-terminal straight from their repo.  The path is relative to the repoURL git repo.   Let us know if you have any other questions.
